import { readFileSync, readdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/*
 * Paths relative to THIS file, not to the working directory.
 *
 * Docusaurus can be run from a parent folder, in which case a relative `docs/`
 * points there and not here. The first attempt failed on exactly that: `ENOENT:
 * scandir 'docs'` while the folder existed - one level down.
 *
 * `import.meta.url` is available even when jiti runs this file as CommonJS;
 * `__dirname` would be the other way round.
 */
const HERE = dirname(fileURLToPath(import.meta.url));
const DOCS = join(HERE, 'docs');

/**
 * Three areas, three sidebars: getting started, components, utilities.
 *
 * Why the component areas are wrapped in categories - and why a plain list is
 * not enough.
 *
 * This used to be six `autogenerated` entries side by side. That looks like
 * the same structure and is a different one: `autogenerated` inserts the
 * CONTENT of a folder at the position where it stands. Six of them side by
 * side means six lots of content and no headings at all.
 *
 * Measured, the result was 56 entries flat on one level where the target shows
 * 36 on two. "Text" appeared three times, "Flex" twice, and the icon page was
 * present but not findable.
 *
 * `dirName: '.'` would be the simple fix and takes everything - including
 * `getting-started` and `utilities`, which have sidebars of their own. So: one
 * category per area, with its label read from the same file Docusaurus would
 * otherwise read it from, `_category_.json`. Copying the label here would be a
 * second truth beside the folder.
 */
const area = (folder: string) => {
  const file = join(DOCS, folder, '_category_.json');
  const { label, position } = JSON.parse(readFileSync(file, 'utf8')) as {
    label: string;
    position: number;
  };
  return {
    type: 'category' as const,
    label,
    position,
    collapsed: true,
    link: undefined,
    items: [{ type: 'autogenerated' as const, dirName: folder }],
  };
};

/**
 * Which folders are component areas: everything under `docs/` except the two
 * that have sidebars of their own. A hand-written list would be out of date
 * with the next area.
 */
const NOT_COMPONENT_AREAS = ['getting-started', 'utilities'];

const componentAreas = readdirSync(DOCS, { withFileTypes: true })
  .filter((e) => e.isDirectory() && !e.name.startsWith('_'))
  .map((e) => e.name)
  .filter((name) => !NOT_COMPONENT_AREAS.includes(name))
  .map(area)
  .sort((a, b) => a.position - b.position)
  .map(({ position: _position, ...rest }) => rest);

const sidebars: SidebarsConfig = {
  gettingStarted: [{ type: 'autogenerated', dirName: 'getting-started' }],
  /*
   * The overview stands above the areas, not inside one. `docs/overview.mdx`
   * therefore lies beside the folders and is put first explicitly;
   * `componentAreas` collects folders only.
   */
  components: [{ type: 'doc', id: 'overview' }, ...componentAreas],
  utilities: [{ type: 'autogenerated', dirName: 'utilities' }],
};

export default sidebars;
